name: Trigger auto deployment for container-app-madbxdn4qccym

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-madbxdn4qccym-AutoDeployTrigger-9ec238fe-758b-41bc-b014-0054775ec0d1.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPMADBXDN4QCCYM_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPMADBXDN4QCCYM_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPMADBXDN4QCCYM_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPMADBXDN4QCCYM_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPMADBXDN4QCCYM_REGISTRY_PASSWORD }}
          containerAppName: container-app-madbxdn4qccym
          resourceGroup: appspacesragappb246bd8a
          imageToBuild: default/container-app-madbxdn4qccym:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


